services:
  postgres:
    image: postgres:13.3
    container_name: quarkus_test
    environment:
      POSTGRES_USER: quarkus_test
      POSTGRES_PASSWORD: quarkus_test
      POSTGRES_DB: quarkus_test
    ports:
      - "15432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U quarkus_test -d quarkus_test"]
      interval: 5s
      timeout: 3s
      retries: 20
